### ISSUE TITLE
No have release for install ?

### ISSUE THREAD

**Issue by liberodark** [armadito/armadito-av#46] opened 2016-06-22 13:59 UTC
Hello,

You don't have release for this software ?

Cordialy

**Comment by fdechelle** [comment] 2016-06-22 14:02
Hello,

No, not yet. But we'll do a beta release very soon, it's in the roadmap.
The release will include installers for windows & source code archives.
Packages for ubuntu and fedora will be available also, but on specific sites (PPA for ubuntu).

Best,

**Comment by liberodark** [comment] 2016-06-22 14:29
Ok thank have contacted teclib for partenership
Im waiting Release have other question what is your database for viral detection ?

**Comment by fdechelle** [comment] 2016-06-22 14:38
databases are associated with scan modules: clamav module use clamav databases (from standard clamav feeds); heuristic module use custom databases. Databases will be updated from a server that is not yet online.

**Comment by liberodark** [comment] 2016-06-22 15:01
Speak in french !

Clamav à 66% de détection viral et beaucoup de faux positif !
Eset lui à 99 % de détection viral et beaucoup moins de faux positif !
Vous allez faire quoi pour améliorer ça ?
Quel est le but en soit de faire un fork de clamav ?
Si vous ne faite pas un système de détection heuristic plus poussé !

Cordialement
PS : Ce sont seulement des questions je souhaite savoir ou va votre projet.

**Comment by fdechelle** [comment] 2016-06-22 15:12
Hi,

1) issues are not the place for discussion about the project; we have a mailing list for that. You can join the list at https://mail.gna.org/listinfo/armadito-av-dev/
2) github is not a french speaking site, it's international. So please use english, so that all non-french speaking people (who are the majority here) can benefit from your nice questions

I'll be pleased to answer your questions on the mailing list. For now, the issue is closed as non-constructive.

Best,

**Closed by fdechelle** 2016-06-22 15:12 UTC
Labels: question
